<? $title = '关于我们'; ?>
<? $bodyClass = 'bg-main'; ?>
<? include template('_layout/header'); ?>

<div class="container about-us">
    <div class="t-box1">
        <p class="tit-black-18 aboutus-title">关于Stay</p>
        <div class="t-body">
            <strong>我们的产品</strong>
            <p style="text-indent:0;margin-bottom:15px;">
                为快速发展的O2O企业提供风险软着陆的整体解决方案
                为亿万网民提供与各种线上线下生活化场景密切相关的保险产品
            </p>

            <strong>我们的愿景</strong>
            <p style="text-indent:0;">『微金融，大保障』</p>
            <p style="text-indent:0;margin-bottom:15px;">
            通过融入我们的产品，使得O2O企业可以专注于为用户提供专业服务，使得亿万用户可以安心享受多样便捷的生活化服务。
            </p>

            <strong>我们的团队</strong>
            <p style="text-indent:0;margin-bottom:15px;">
            Stay的创始团队，有来自平安等顶尖保险企业资深高管与精算师，亦有来自腾讯等知名互联网公司的资深管理人员、海量用户产品运营专家、高级工程师等。<br />
            团队成立之初，便获得了知名投资机构的千万级的天使投资，并与腾讯、大众点评等多家互联网公司缔结了合作关系。目前，已开始洽谈新一轮融资。
            </p>
        </div>
    </div>
</div>

<? include template('_layout/footer'); ?>